services:
  # クライアントアプリ
  fe:
    container_name: fe
    build:
      context: .
      dockerfile: ./apps/fe/Dockerfile
    command: npm run dev
    restart: always
    volumes:
      - ./apps/fe:/app/apps/fe
      # Volume Tick
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app_network
  # BFFサーバー
  bff:
    container_name: bff
    build:
      context: .
      dockerfile: ./apps/bff/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true