version: "3"

services:
  fe:
    container_name: fe
    build:
      context: .
      dockerfile: ./apps/fe/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  bff:
    container_name: bff
    build:
      context: .
      dockerfile: ./apps/bff/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true